version: '3'
services:
  finance_db:
    image: postgres
    container_name: finance
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "$DATABASE_PORT:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  finance_db_test:
    image: postgres
    container_name: finance_test
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: finance_test
    ports:
      - "5434:5432"
