version: '3'
services:
  finance_db:
    image: postgres
    container_name: finance
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
