name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  check: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Create .env.test file
        run: echo "DATABASE_URL=postgresql://admin:pass@localhost:5434/finance_test" >> .env.test

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint:check
        
      - name: Test
        run: npm run test
    
    migrate:
      runs-on: ubuntu-latest
      needs: check
      environment: production

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
           node-version: "20"
        
        - name: install dependencies
          run: npm install

        - name: Make envfile
          uses: SpicyPizza/create-envfile@v2.0
          with:
            envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}

        - name: Run migrations
          run: npx prisma migrate deploy