name: Deploy
on: 
  push:
    branches:
      - main
jobs:
  check: 
    runs-on: ubuntu-latest
    setps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        run: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Lint
        run: npm run lint:check
        
      - name: Test
        run: npm run test